apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: echos.echo.rhte2019.io
spec:
  group: echo.rhte2019.io
  names:
    kind: Echo
    listKind: EchoList
    plural: echos
    singular: echo
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            message:
              description: Message is the message which Echo should print to STDOUT
              type: string
            namespace:
              description: Namespace is the namespace in which an Echo should be deployed
              type: string
            replicas:
              description: Replicas is the number of Echos which should exist
              format: int32
              type: integer
            version:
              description: Version is the version tag on the application image to
                use, default is 'latest'
              type: string
          required:
          - message
          - namespace
          type: object
        status:
          properties:
            nodes:
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
